name: CI build for docker action
on:
  push:
    branches: main
    paths: [hello-world-docker-action/**] # will trigger on every push to main in this path
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3.2.2 # mandatory for local actions

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@vimst38'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
