name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:  # call another worflow
    uses: ./.github/workflows/reusable.yml  # specifying full path regarding github
    with:  # varibale input
      who-to-greet: '@moricev' # name of the input parameter

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
